# Generated by Django 3.2.7 on 2022-01-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cittu', '0002_auto_20220131_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunitreport',
            name='introduction',
            field=models.CharField(max_length=200),
        ),
    ]
