# Generated by Django 3.2.7 on 2022-02-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cittu', '0003_alter_subunitreport_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subunitreport',
            name='content',
        ),
        migrations.AlterField(
            model_name='subunitreport',
            name='achievement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subunitreport',
            name='challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subunitreport',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subunitreport',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
